config/routes.rb
Rails.application.routes.draw do
  get '/designs/new' => 'designs#new'

  get '/designs/:id' => 'designs#app'

  root 'sessions#new'

  get '/login' => 'sessions#new', :as => 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', :as => 'logout'
  get '/logout' => 'sessions#destroy'

  resources :charges
  resources :orders
  resources :messages
  resources :elements
  resources :designs
  resources :users
  
end

app/models/design.rb
class Design < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :orders
  has_many :messages
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index

    if !@current_user
        redirect_to login_path
    end

    # if @current_user
    #     @designs = [];
    #     userDesignIds = DesignsUsers.where(user_id: @current_user.id);
    #     # loop throuch each design id and push it to an array
    #     userDesignIds.each do | item |
    #         currentDesign = Design.find(item.design_id);
    #         @designs.push(currentDesign);
    #     end
    # end
    
    @designs = Design.all


  end

  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  def app
    @current_design = params[:id]
    @current_user = User.find_by( :id => session[:user_id] )
  end


  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)

    respond_to do |format|
      if @design.save
        DesignsUsers.create( {design_id: @design.id, user_id: session[:user_id]} )
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    @design.destroy
    respond_to do |format|
      format.html { redirect_to designs_url, notice: 'Design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:canvas_data, :url)
    end
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="designName">
    <%= f.text_field :url, :class => "form-control", :placeholder => "Name your design" %>
  </div>
    <br>
<% end %>

app/views/designs/app.html.erb
<div id="main">
  <div class="spinnerBlue">
    <%= image_tag( "spinnerBlue.gif", :id => "spinnerBlueImage" ) %>
  </div>
</div>

<script>
  var app = app || {};
  app.currentUser = <%= @current_user.to_json.html_safe %>;
  app.currentDesignID = <%= @current_design.to_json.html_safe %>;
</script>



<script id="appViewTemplate" type="html/template">
  <div class="allViewsContainer">
      <div id="elementsContainer">Elements go here</div>
      <div id="designContainer">Designs go here</div>
      <div id="chatContainer"></div>
  </div>
</script>

<script id="elementsViewTemplate" type="html/template">
    <div id="elementsMenu">
    </div>
    <div id="elementsList">
    </div>
    <div id="elementsAdd">
    </div>
</script>

<script id="elementsMenuTemplate"  type="html/template">
    <ul></ul>
</script>

<script id="elementsMenuItemTemplate" type="html/template">
    <li data-type="<%%= type %>">
        <div class="typeSymbolContainer"> <span class="typeSymbol"></span> </div> <a href="#"> <%%= type %> </a>
    </li>
</script>

<script id="elementListTemplate" type="html/template" style="display: none;">
    <ul></ul>
</script>

<script id="elementItemView" type="html/template">
    <div class="elementItemContainer" data-type="<%%= type %>" data-id="<%%= id %>">
        <div class="elementItemType">
            <div class="elementItemCircle">
            </div>
        </div>
        <div class="elementItemImage">
                <div class="elementItemImageInner">
                    <img src="<%%= image %>" />
                </div>
        </div>
        <div class="elementItemTitle"> <%%= title %> </div>
    </div>
</script>

<!-- DESIGN AREA -->

<script id="memberViewTemplate" type="html/template">
        <div class="memberName"> <%%= name %> </div>
</script>

<script id="membersViewTemplate" type="html/template">
    <span id="membersListTitle"> Squad </span>
    <ul id="memberList">
    </ul>
</script>

<script id="toolsViewTemplate" type="html/template">
    <div class="cursorModes col-md-2">
        <div class="cursorModeTitle h4 small"> Brush mode </div>
        <input class = "cursorRadio" id ="brushRadio" type="radio" name="cursorMode" value="brush" checked> Brush<br>
        <input class = "cursorRadio" id = "selectRadio" type="radio" name="cursorMode" value="select"> Select<br>
    </div>
    <div class="brushSettings col-md-4">
        <div class="cursorModeTitle h4 small"> Brush settings </div>
        <label for="fader">Size</label>
        <input class="brushSizeInput" type="range" min="5" max="50" value="10" id="fader">
        <label for="fader">Color</label></br>
        <input id="colorPicker" value="000000" class="jscolor {width:243, height:150, position:'right', borderColor:'#FFF', insetColor:'#FFF', backgroundColor:'#666'}"><br/>
    </div>
    <div class="toolsControls col-md-6">
        <div class="cursorModeTitle h4 small"> Controls </div>
        <button id = "undoButton" type="button" class="btn btn-default"> Undo</button>
        <a id = "downloadLink" > <button type="button" class="btn btn-default">Download Image</button> </a>
        <button id = "saveButton" type="button" class="btn btn-default"> Save Design </button>
        <button id = "buyButton" type="button" class="btn btn-success"> Buy Design </button>
        <button id = "deleteButton" type="button" class="btn btn-danger"> Delete </button>
    </div>

</script>

<script id="designViewTemplate" type="html/template">

    <div id = "toolsContainer"> </div>
    <canvas id="myCanvas" resize></canvas>
    <div id="membersContainer"> </div>
</script>




<!-- CHAT AREA -->
<script id="chatViewTemplate" type="html/template">
    <div id="chatMessages"></div>
    <div id="chatInput">Message input form goes here</div>
</script>

<script id="chatMessagesTemplate" type="html/template"></script>

<script id="chatInputFormTemplate" type="html/template">
    <input type="text" placeholder="Message squad" id="chatInputForm"></input>
</script>

<!--
********************************************************************************
CHECKOUT VIEW TEMPLATE *********************************************************
********************************************************************************
-->


<script id="checkOutViewTemplate" class="container" type="html/template">
  <div class="row">
    <div id="designToBuy" class="col-sm-4"></div>
    <div id="paymentInfo" class="col-sm-8"></div>
  </div>
</script>

<script id="designToBuyTemplate" type="html/template">

// Your design here
// current order goes here

// selected stuff

</script>

<script id="paymentInfoTemplate" type="html/template">

<%= form_tag charges_path do %>
<h1>Order Form</h1>
    <div class="form-group">
        <label for="exampleInputEmail1">Swag</label>
        <select class="form-control">
            <option>Shirt</option>
            <option>Poster</option>
            <option>Mug</option>
        </select>
    </div>
    <div class="form-group">
        <label for="size">Size</label>
        <select class="form-control">
        <option>XS</option>
        <option>S</option>
        <option>M</option>
        <option>L</option>
        <option>XL</option>
        </select>
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <select class="form-control">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div>
    <hr>
    <div class="form-group">
        <label for="quantity">Personal Details</label>
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="First Name">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Last Name">
    </div>
    <div class="form-group">
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
    </div>
    <hr>
    <div class="form-group">
        <label for="exampleInputEmail1">Address</label>
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Address">
    </div>
    <div class="form-group">
        <select class="form-control">
            <option>NSW</option>
            <option>VIC</option>
            <option>ACT</option>
            <option>SA</option>
            <option>TAS</option>
            <option>WA</option>
            <option>SA</option>
            <option>NT</option>
        </select>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="City">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Postcode">
    </div>
    <button class="btn btn-default navigateToDesign"> Go back to design </button>

<% end %>

</script>


<!--
swag
size
quantity
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
First Name *
Last Name *
Email *
Phone Number *
Address Line 1 *
Address Line 2
Address Line 3
Country :Australia
City *
Postal Code *
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
PAY NOW
-->

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<%= stylesheet_link_tag 'designs' %>

<p id="notice"><%= notice %></p>

<div class="allDesignsContainer">

    <% @designs.each do |design| %>
      <%= link_to(image_tag(design.url, :class => "thumbnail" ), design_path(design)) %>
    <% end %>

</div>

app/views/designs/new.html.erb
<%= stylesheet_link_tag 'designs' %>

<div class="newDesignForm">

<%= render 'form' %>

</div>

app/views/designs/show.html.erb
<%= stylesheet_link_tag 'designs' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Canvas data:</strong>
  <%= @design.canvas_data %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag( @design.url, :class => 'feature') %>
</p>

<p>
  <strong>Designers:</strong>
  <% @design.users.each do |u| %>
    <%= u.name %>
  <% end %>


</p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>